package com.itdr.changyonglei.Demo2;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;

public class BigIntegerD {
    public static void main(String[] args) throws ParseException {
        BigInteger bi1 = new BigInteger("100");
        BigInteger bi2 = new BigInteger("50");
        System.out.println(bi1.add(bi2));
        System.out.println(bi1.subtract(bi2));
        System.out.println(bi1.multiply(bi2));
        System.out.println(bi1.divide(bi2));
        BigInteger[] bis = bi1.divideAndRemainder(bi2);
        System.out.println("商：" + bis[0]);
        System.out.println("余数：" + bis[1]);
        System.out.println("--------------------------");

        System.out.println(0.09 + 0.01);
        System.out.println(1 - 0.32);
        System.out.println(1.015 * 100);
        System.out.println(1.301 / 100);
        System.out.println(1.0 - 0.12);
        System.out.println("-------------");
        BigDecimal bd1 = new BigDecimal("0.09");
        BigDecimal bd2 = new BigDecimal("0.01");
        System.out.println(bd1.add(bd2));
        BigDecimal bd3 = new BigDecimal("1.0");
        BigDecimal bd4 = new BigDecimal("0.32");
        System.out.println(bd3.subtract(bd4));
        BigDecimal bd5 = new BigDecimal("1.015");
        BigDecimal bd6 = new BigDecimal("100");
        System.out.println(bd5.multiply(bd6));
        BigDecimal bd7 = new BigDecimal("1.301");
        BigDecimal bd8 = new BigDecimal("100");
        System.out.println(bd7.divide(bd8));
        System.out.println(bd7.divide(bd8, 3, BigDecimal.ROUND_HALF_UP));
        System.out.println(bd7.divide(bd8, 8, BigDecimal.ROUND_HALF_UP));
        System.out.println("---------------------------------------------");
        Date d = new Date();
        System.out.println(d);
        long time = System.currentTimeMillis();
        long time2 = 1000 * 60 * 60;
        Date d2 = new Date(time);
        System.out.println(d2);
        Date d3 = new Date(time2);
        System.out.println(d3);
        System.out.println("------------------------");
        Date d4 = new Date();
        long t1 = d4.getTime();
        System.out.println(t1);
        System.out.println(System.currentTimeMillis());
        System.out.println(d4);
        d4.setTime(1000);
        System.out.println(d4);
        System.out.println("-------------------");
        Date d5 = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy年MM月dd日 HH:mm:ss");
        String s2 = sdf.format(d5);
        System.out.println(s2);
        String str = "2008-08-08 12:12:12";
        SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date dd = sdf2.parse(str);
        System.out.println(dd);
        System.out.println("-----------------------------");
        Scanner sc = new Scanner(System.in);
        System.out.println("你的出生年月日：");
        String line = sc.nextLine();
        SimpleDateFormat sdf3 = new SimpleDateFormat("yyyy-MM-dd");
        Date d6 = sdf3.parse(line);
        long myTime = d6.getTime();
        long nowTime = System.currentTimeMillis();
        long time3 = nowTime - myTime;
        long day = time3 / 1000 / 60 / 60 / 24;
        System.out.println("你来到这个世界" + day + "天");
        System.out.println("==================================");
        Calendar c = Calendar.getInstance();
        int year = c.get(Calendar.YEAR);
        int month = c.get(Calendar.MONTH);
        int date = c.get(Calendar.DATE);
        System.out.println(year + "年" + (month + 1) + "月" + date + "日");
        c.add(Calendar.YEAR, -3);
        year = c.get(Calendar.YEAR);
        month = c.get(Calendar.MONTH);
        date = c.get(Calendar.DATE);
        System.out.println(year + "年" + (month + 1) + "月" + date + "日");
        c.add(Calendar.YEAR, 5);
        c.add(Calendar.DATE, -10);
        year = c.get(Calendar.YEAR);
        month = c.get(Calendar.MONTH);
        date = c.get(Calendar.DATE);
        System.out.println(year + "年" + (month + 1) + "月" + date + "日");
        c.set(2011, 11, 11);
        year = c.get(Calendar.YEAR);
        month = c.get(Calendar.MONTH);
        date = c.get(Calendar.DATE);
        System.out.println(year + "年" + (month + 1) + "月" + date + "日");
        System.out.println("-------------------------------------------");
        Scanner sc2=new Scanner(System.in);
        System.out.println("年份：");
        int year2=sc2.nextInt();
        Calendar c2=Calendar.getInstance();
        c2.set(year2,2,1);
        c2.add(Calendar.DATE,-1);
        System.out.println(c2.get(Calendar.DATE));
        System.out.println("---------------------------");
    }
}
